<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'id' => 1,
                'title' => 'Melange Casual Black',
                'slug' => 'melange-casual-black',
                'summary' => '<p><span style="font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;">"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</span><br></p>',
                'description' => '<h3 style="margin: 15px 0px; padding: 0px; font-weight: 700; font-size: 14px; font-family: &quot;Open Sans&quot;, Arial, sans-serif;">The standard Lorem Ipsum passage, used since the 1500s</h3><p style="margin-right: 0px; margin-bottom: 15px; margin-left: 0px; padding: 0px; text-align: justify; font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px;">"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p>',
                'photo' => '/storage/photos/1/Products/405b7-pmtk004t.jpg,/storage/photos/1/Products/43f35-2_2.jpg',
                'stock' => 5,
                'size' => 'S,M,XL',
                'condition' => 'new',
                'status' => 'active',
                'price' => 600.00,
                'discount' => 10.00,
                'is_featured' => 1,
                'cat_id' => 1,
                'child_cat_id' => 4,
                'brand_id' => 4,
                'created_at' => Carbon::parse('2020-08-14 04:38:26'),
                'updated_at' => Carbon::parse('2020-08-14 04:42:46'),
            ],
            [
                'id' => 2,
                'title' => 'White Sports Casual T-',
                'slug' => 'white-sports-casual-t',
                'summary' => '<p><span style="font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;">But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and</span><br></p>',
                'description' => '<h3 style="margin: 15px 0px; padding: 0px; font-weight: 700; font-size: 14px; font-family: &quot;Open Sans&quot;, Arial, sans-serif;">The standard Lorem Ipsum passage, used since the 1500s</h3><p style="margin-right: 0px; margin-bottom: 15px; margin-left: 0px; padding: 0px; text-align: justify; font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px;">"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua...</p>',
                'photo' => '/storage/photos/1/Products/1d60f-2.jpg',
                'stock' => 3,
                'size' => 'XL',
                'condition' => 'hot',
                'status' => 'active',
                'price' => 400.00,
                'discount' => 4.00,
                'is_featured' => 1,
                'cat_id' => 1,
                'child_cat_id' => 4,
                'brand_id' => 2,
                'created_at' => Carbon::parse('2020-08-14 04:40:21'),
                'updated_at' => Carbon::parse('2020-08-14 06:26:01'),
            ],
            [
                'id' => 3,
                'title' => 'Summer Round Neck T',
                'slug' => 'summer-round-neck-t',
                'summary' => '<p><span style="font-family: "Open Sans", Arial, sans-serif; font-size: 14px; text-align: justify;">"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore</span><br></p>',
                'description' => '<h3 style="margin: 15px 0px; padding: 0px; font-weight: 700; font-size: 14px; font-family: "Open Sans", Arial, sans-serif;">Section 1.10.32 of "de Finibus Bonorum et Malorum", written by Cicero in 45 BC</h3>...', // Adicione o restante da descrição aqui
                'photo' => '/storage/photos/1/Products/02090-pms003a.jpg,/storage/photos/1/Products/01f42-pwt004b.jpg,/storage/photos/1/Products/01bc5-mpd006b.jpg,/storage/photos/1/Products/0122b-wsd000t.jpg',
                'stock' => 6,
                'size' => 'S,M',
                'condition' => 'hot',
                'status' => 'active',
                'price' => 3000.00,
                'discount' => 5.00,
                'is_featured' => 0,
                'cat_id' => 2,
                'child_cat_id' => NULL,
                'brand_id' => 2,
                'created_at' => '2020-08-14 05:57:48',
                'updated_at' => '2020-08-14 05:57:48',
            ],
            [
                'id' => 4,
                'title' => 'Melange Ethnic Kurthi',
                'slug' => 'melange-ethnic-kurthi',
                'summary' => '<p><span style="font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;">At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident,</span><br></p>',
                'description' => '<h3 style="margin: 15px 0px; padding: 0px; font-weight: 700; font-size: 14px; font-family: &quot;Open Sans&quot;, Arial, sans-serif;">Section 1.10.32 of "de Finibus Bonorum et Malorum", written by Cicero in 45 BC</h3><p style="margin-right: 0px; margin-bottom: 15px; margin-left: 0px; padding: 0px; text-align: justify; font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px;">"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo...</p>',
                'photo' => '/storage/photos/1/Products/0a402-image4xxl-3-.jpg,/storage/photos/1/Products/2282b-wsd008t.jpg,/storage/photos/1/Products/21951-image4xxl.jpg',
                'stock' => 5,
                'size' => 'XL',
                'condition' => 'default',
                'status' => 'active',
                'price' => 4000.00,
                'discount' => 50.00,
                'is_featured' => 0,
                'cat_id' => 2,
                'child_cat_id' => NULL,
                'brand_id' => 1,
                'created_at' => Carbon::parse('2020-08-14 06:04:13'),
                'updated_at' => Carbon::parse('2020-08-14 06:04:13'),
            ],
            [
                'id' => 5,
                'title' => 'Cotton High Quality Kurt',
                'slug' => 'cotton-high-quality-kurt',
                'summary' => '<p><span style="font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;">At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident,</span><br></p>',
                'description' => '<h3 style="margin: 15px 0px; padding: 0px; font-weight: 700; font-size: 14px; font-family: &quot;Open Sans&quot;, Arial, sans-serif;">Section 1.10.33 of "de Finibus Bonorum et Malorum", written by Cicero in 45 BC</h3><p style="margin-right: 0px; margin-bottom: 15px; margin-left: 0px; padding: 0px; text-align: justify; font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px;">"At vero eos et accusamus...</p>',
                'photo' => '/storage/photos/1/Products/0455e-c1.jpg,/storage/photos/1/Products/04ec4-pmtk001t.jpg,/storage/photos/1/Products/086c2-a1.jpg,/storage/photos/1/Products/09a16-mpd000t_6.jpg,/storage/photos/1/Products/0c2d2-wbk012c-royal-blue.jpg',
                'stock' => 0,
                'size' => 'M,XL',
                'condition' => 'new',
                'status' => 'active',
                'price' => 4000.00,
                'discount' => 10.00,
                'is_featured' => 0,
                'cat_id' => 3,
                'child_cat_id' => NULL,
                'brand_id' => 3,
                'created_at' => '2020-08-14 06:10:52',
                'updated_at' => '2020-08-14 09:37:36',
            ],
            [
                'id' => 6,
                'title' => 'Ladies Cotton Kurti Sha',
                'slug' => 'ladies-cotton-kurti-sha',
                'summary' => '<p><span style="font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;">"But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system,</span><br></p>',
                'description' => '<h3 style="margin: 15px 0px; padding: 0px; font-weight: 700; font-size: 14px; font-family: &quot;Open Sans&quot;, Arial, sans-serif;">Section 1.10.33 of "de Finibus Bonorum et Malorum", written by Cicero in 45 BC</h3><p style="margin-right: 0px; margin-bottom: 15px; margin-left: 0px; padding: 0px; text-align: justify; font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px;">"At vero eos et accusamus...</p>',
                'photo' => '/storage/photos/1/Products/6a8b5-wsd013t.jpg,/storage/photos/1/Products/5ded8-image1xxl-5-.jpg,/storage/photos/1/Products/74840-image4xxl-6-.jpg',
                'stock' => 6,
                'size' => 'M,L',
                'condition' => 'hot',
                'status' => 'active',
                'price' => 6000.00,
                'discount' => 3.00,
                'is_featured' => 1,
                'cat_id' => 3,
                'child_cat_id' => NULL,
                'brand_id' => 4,
                'created_at' => '2020-08-14 06:13:20',
                'updated_at' => '2020-08-14 06:31:42',
            ],
            [
                'id' => 7,
                'title' => 'GRAY BABY ROMPERS',
                'slug' => 'gray-baby-rompers',
                'summary' => '<p><span style="font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;">"But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system,</span><br></p>',
                'description' => '<h3 style="margin: 15px 0px; padding: 0px; font-weight: 700; font-size: 14px; font-family: &quot;Open Sans&quot;, Arial, sans-serif;">1914 translation by H. Rackham</h3><p style="margin-right: 0px; margin-bottom: 15px; margin-left: 0px; padding: 0px; text-align: justify; font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px;">"But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness...</p>',
                'photo' => '/storage/photos/1/Products/08ec9-n3.jpg,/storage/photos/1/Products/07e30-mtk006b.jpg,/storage/photos/1/Products/18b18-wbk003b.jpg',
                'stock' => 0,
                'size' => 'L',
                'condition' => 'hot',
                'status' => 'active',
                'price' => 1999.00,
                'discount' => 3.00,
                'is_featured' => 0,
                'cat_id' => 3,
                'child_cat_id' => NULL,
                'brand_id' => 1,
            ],
            [
                'id' => 8,
                'title' => 'Baby Girls\' 2-Piece Yell',
                'slug' => 'baby-girls-2-piece-yell',
                'summary' => '<p><span style="font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;">"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit,</span><br></p>',
                'description' => '<h3 style="margin: 15px 0px; padding: 0px; font-weight: 700; font-size: 14px; font-family: &quot;Open Sans&quot;, Arial, sans-serif;">1914 translation by H. Rackham</h3><p style="margin-right: 0px; margin-bottom: 15px; margin-left: 0px; padding: 0px; text-align: justify; font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px;">"But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born...</p>',
                'photo' => '/storage/photos/1/Products/calvin-klein.jpg,/storage/photos/1/Products/calvin.jpg,/storage/photos/1/Products/d3fdb-image2xxl-4-.jpg',
                'stock' => 1,
                'size' => 'S',
                'condition' => 'new',
                'status' => 'active',
                'price' => 200.00,
                'discount' => 0.00,
                'is_featured' => 0,
                'cat_id' => 3,
                'child_cat_id' => NULL,
                'brand_id' => 2,
                'created_at' => '2020-08-14 06:25:42',
                'updated_at' => '2020-08-14 09:37:36',
            ],
            [
                'id' => 9,
                'title' => 'Lorem Ipsum is simply',
                'slug' => 'lorem-ipsum-is-simply',
                'summary' => '<p><strong style="margin: 0px; padding: 0px; font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;">Lorem Ipsum</strong><span style="font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;">&nbsp;is simply dummy text of the printing and typesetting industry.</span><br></p>',
                'description' => '<p><strong style="margin: 0px; padding: 0px; font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;">orem Ipsum</strong><span style="font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;">&nbsp;is simply dummy text of the printing and typesetting industry...</span></p>',
                'photo' => '/storage/photos/1/Products/0455e-c1.jpg,/storage/photos/1/Products/04776-pms000a.jpg,/storage/photos/1/Products/04ec4-pmtk001t.jpg,/storage/photos/1/Products/032f0-image3xxl-1-.jpg',
                'stock' => 4,
                'size' => 'S,M,XL',
                'condition' => 'new',
                'status' => 'active',
                'price' => 200.00,
                'discount' => 5.00,
                'is_featured' => 0,
                'cat_id' => 2,
                'child_cat_id' => NULL,
                'brand_id' => 3,
            ],
            [
                'id' => 10,
                'title' => 'Lorem Ipsum is simply',
                'slug' => 'lorem-ipsum-is-simply-2008183507-655',
                'summary' => '<p><strong style="margin: 0px; padding: 0px; font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;">Lorem Ipsum</strong> ... </p>',
                'description' => '<p><strong style="margin: 0px; padding: 0px; font-family: &quot;Open Sans&quot;, Arial, sans-serif; font-size: 14px; text-align: justify;">Lorem Ipsum</strong> ... </p>',
                'photo' => '/storage/photos/1/Products/01f42-pwt004b.jpg,/storage/photos/1/Products/02090-pms003a.jpg,/storage/photos/1/Products/032f0-image3xxl-1-.jpg',
                'stock' => 3,
                'size' => 'L,XL',
                'condition' => 'hot',
                'status' => 'active',
                'price' => 300.00,
                'discount' => 10.00,
                'is_featured' => 0,
                'cat_id' => 1,
                'child_cat_id' => 4,
                'brand_id' => 3,
                'created_at' => '2020-08-17 20:50:07',
                'updated_at' => '2020-08-17 20:50:07',
            ]
        ]);
    }
}
